alias glgl='glg --author=Liang'
alias nb='$HOME/dev/scripts/nextBus/toOffice.sh'
alias nexta='ssh ec2 -t "tail /var/log/apache2/next/access.log"'
alias nexte='ssh ec2 -t "tail /var/log/apache2/next/error.log"'
alias psh='php -S 192.168.1.6:8888'
alias sdr2='screen -dR lliu2'
alias sdr='screen -dR lliu1'
alias sdre2='ssh ec2 -t "screen -dR lliu2"'
alias sdre='ssh ec2 -t "screen -dR lliu1"'
alias sr='$HOME/dev/scripts/reminder/showReminder.sh'
alias ud2='diskutil unmountdisk /dev/disk2'
alias wh='which'
