alias glgl='glg --author=Liang'
alias sdr1='screen -dR lliu1'
alias sdr2='screen -dR lliu2'
alias sdre2='ssh ec2 -t "screen -dR lliu2"'
alias sdre='ssh ec2 -t "screen -dR lliu1"'
alias ud2='diskutil unmountdisk /dev/disk2'
alias wh='which'
